var carro = new Carro("Volkswagen", "Gol bola 2005");
carro.Ligar();
carro.Acelerar();
carro.Frear();
carro.Desligar();
System.Console.WriteLine();
var bicicleta = new Bicicleta("caloi", "BMX");
bicicleta.Ligar();
bicicleta.Acelerar();
bicicleta.Desligar();
